### ISSUE TITLE
ModuleNotFoundError 'distutils'

### ISSUE THREAD

**Issue by shakirc2983** [deniselezi/pcs-crawler#9]
Python version: 3.13.0

On the main branch. tried running the command

`(venv) PS C:\projects\pcs-crawler> py crawler.py https://github.com/SpoonLabs/astor 2`

Output
```
Traceback (most recent call last):
  File "C:\projects\pcs-crawler\crawler.py", line 10, in <module>
    from pcs_spellchecker.spellchecker import Spellchecker
  File "C:\projects\pcs-crawler\pcs_spellchecker\spellchecker.py", line 1, in <module>
    import language_tool_python
  File "C:\projects\pcs-crawler\venv\Lib\site-packages\language_tool_python\__init__.py", line 8, in <module>
    from .server import LanguageTool, LanguageToolPublicAPI
  File "C:\projects\pcs-crawler\venv\Lib\site-packages\language_tool_python\server.py", line 15, in <module>
    from .download_lt import download_lt, LTP_DOWNLOAD_VERSION
  File "C:\projects\pcs-crawler\venv\Lib\site-packages\language_tool_python\download_lt.py", line 16, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils'
```

**Comment by deniselezi** [comment]
Seems to be related to your version of Python, https://stackoverflow.com/questions/77233855/why-did-i-get-an-error-modulenotfounderror-no-module-named-distutils.
Can you try installing the `setuptools` package? If this solves the problem we can add it as a dependency.
